# Koyeb deployment configuration

services:
  - name: scafffood-api
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
      context: .
    ports:
      - port: 8080
        protocol: http
    env:
      - key: PORT
        value: "8080"
    regions:
      - fra
    instance_type: nano
    scaling:
      min: 1
      max: 1
